import { LANDMARK_INDICES as L } from './types';

export const WEBCAM = {
  WIDTH: 640,
  HEIGHT: 480,
  FPS: 30,
  FACING_MODE: 'user',
} as const;

export const INFERENCE = {
  EVERY_NTH_FRAME: 2,
  MAX_HANDS: 2,
  MIN_HAND_DETECTION_CONFIDENCE: 0.50,
  MIN_TRACKING_CONFIDENCE: 0.30,
  MODEL_PATH: `${import.meta.env.BASE_URL}models/hand_landmarker.task`,
  DELEGATE: 'CPU' as const,
  WORKER_TIMEOUT_MS: 8000,
  WORKER_RESTART_DELAY_MS: 2000,
  MAX_WORKER_RESTARTS: 3,
  STALE_FRAME_MS: 800,
} as const;

export const GESTURE = {
  COOLDOWN_MS: 150,
  CLEAR_HOLD_MS: 1200,
  MIN_CONFIDENCE: 0.35,
  FINGER_EXTENSION_THRESHOLD: 0.08,
  THUMB_EXTENSION_THRESHOLD: 0.12,
  HAND_SCALE_REFERENCE: 0.22,
  FINGER_ANGLE_CURLED_MIN: 0.72,
  FINGER_ANGLE_OPEN_MAX: 0.60,
  EXTENSION_SCORE_MIN: 0.25,
  DRAWING_INDEX_SCORE_MIN: 0.35,
  DRAWING_CURLED_SCORE_MAX: 0.20,
  DRAWING_THUMB_CURLED_MAX: 0.35,
  HEX_ASYMMETRY_DRAWING: 2.0,
  ACTIVATE_FRAMES: 3,
  DEACTIVATE_FRAMES: 4,
  LATCH_MS: 600,
} as const;

export const ACTION_MAPPING: Record<string, string> = {
  drawing: 'DRAW',
  cursor: 'CURSOR',
  eraser: 'ERASE',
  idle: 'IDLE',
  swipe_left: 'PREV_SCENE',
  swipe_right: 'NEXT_SCENE',
} as const;

export const SMOOTHING = {
  MIN_CUTOFF: 1.5,
  BETA: 0.08,
  D_CUTOFF: 1.2,
  PREDICTION_HORIZON: 0.008,
  MOTION_SMOOTHING: 0.15,
  ADAPTIVE_SPEED_FACTOR: 0.15,
} as const;

export const DRAWING = {
  DEFAULT_WIDTH: 2,
  MIN_WIDTH: 1,
  MAX_WIDTH: 8,
  MIN_POINT_DISTANCE: 0.0008,
  CURVE_QUALITY: 4,
  UNDO_DEPTH: 50,
  MAX_POINTS_PER_STROKE: 3000,
  RIBBON_CAP_SEGMENTS: 3,
} as const;

export const RENDER = {
  BG_COLOR: 0x0a0a0f,
  TARGET_FPS: 60,
  TRACKING_DECOUPLE_FACTOR: 0.5,
  STROKE_GLOW_ENABLED: false,
  MOTION_TRAIL_ENABLED: false,
  HAND_AURA_ENABLED: false,
} as const;

export const PERFORMANCE = {
  TARGET_FPS: 60,
  LOW_FPS_THRESHOLD: 20,
  ADAPTIVE_QUALITY_INTERVAL_MS: 5000,
  FPS_SAMPLE_WINDOW: 60,
  MAX_MEMORY_ITEMS: 10000,
} as const;

export const KIOSK = {
  IDLE_RESET_MS: 120000,
  FULLSCREEN_ENABLED: true,
  CONTEXT_MENU_BLOCKED: true,
  KEYBOARD_SHORTCUTS_BLOCKED: true,
  WATCHDOG_INTERVAL_MS: 5000,
  MAX_CRASHES_BEFORE_RELOAD: 5,
} as const;

export const Z_LAYERS = {
  BACKGROUND: -1,
  CANVAS: 0,
  STROKES: 1,
  STROKE_GLOW: 2,
  HAND_OVERLAY: 10,
  GESTURE_INDICATOR: 20,
  UI_OVERLAY: 100,
} as const;

export const FINGER_TIP_INDICES: number[] = [
  L.THUMB_TIP, L.INDEX_TIP, L.MIDDLE_TIP, L.RING_TIP, L.PINKY_TIP,
];

export const FINGER_MCP_INDICES: number[] = [
  L.THUMB_MCP, L.INDEX_MCP, L.MIDDLE_MCP, L.RING_MCP, L.PINKY_MCP,
];

export const FINGER_PIP_INDICES: number[] = [
  L.THUMB_IP, L.INDEX_PIP, L.MIDDLE_PIP, L.RING_PIP, L.PINKY_PIP,
];

export const INTERACTION = {
  PALETTE_ZONE_X: 0.12,
  PALETTE_DEACTIVATE_X: 0.22,
  PALETTE_Y_MIN: 0.10,
  PALETTE_Y_MAX: 0.70,
  HOVER_ACTIVATION_DELAY_MS: 120,
  CURSOR_EASING_FACTOR: 0.22,
  DRAW_STOP_ZONE_Y: -0.02,
  PALETTE_SNAP_SPEED: 0.25,
  CURSOR_MODE_OPACITY: 0.8,
  DRAW_MODE_OPACITY: 0.95,
  ERASE_MODE_OPACITY: 0.7,
  ATTRACT_MODE_IDLE_MS: 15000,
  UI_TOP_MARGIN: 0.0,
} as const;

export const OCCLUSION = {
  POSE_MEMORY_SIZE: 5,
  MAX_EXTRAPOLATION_MS: 300,
  CONFIDENCE_DECAY_RATE: 0.2,
} as const;

export const ADAPTIVE = {
  HISTORY_SIZE: 20,
  BASE_CONFIDENCE_THRESHOLD: 0.35,
  SPEED_ADAPTATION_RATE: 0.12,
  STABILITY_ADAPTATION_RATE: 0.15,
  FAST_MOTION_THRESHOLD: 0.06,
  SLOW_MOTION_THRESHOLD: 0.01,
} as const;

export const CONFIDENCE = {
  SMOOTHING_ALPHA: 0.35,
  DECAY_RATE_PER_MS: 0.0003,
  GATE_THRESHOLD: 0.20,
  HIGH_CONFIDENCE: 0.70,
  HISTORY_SIZE: 10,
  FAST_DECAY_THRESHOLD: 0.03,
  FAST_DECAY_RATE: 0.0006,
} as const;

export const EDGE = {
  SAFE_MARGIN: 0.05,
  DAMPING_ZONE: 0.03,
  BOTTOM_EXTRA_MARGIN: 0.08,
  HIGH_DAMPING_THRESHOLD: 0.7,
  FULL_DAMPING: 0.2,
  GESTURE_SENSITIVITY_WEIGHT: 0.6,
  CURSOR_DAMPING_WEIGHT: 0.4,
  BOTTOM_CONFIDENCE_PENALTY: 0.15,
  EDGE_CONFIDENCE_FLOOR: 0.25,
} as const;

export const EXTRAPOLATION = {
  MAX_BLEND_FRAMES: 5,
  VELOCITY_DAMPING: 0.85,
  DRIFT_CAP: 0.03,
  RECOVERY_BLEND_ALPHA: 0.35,
  MAX_PREDICTION_SPEED: 0.008,
} as const;

export const CALIBRATION = {
  AUTO_CALIBRATION_FRAMES: 30,
  CALIBRATION_SAMPLE_INTERVAL_MS: 100,
  BOTTOM_EDGE_SAMPLES: 10,
  PERSPECTIVE_SAMPLE_REGIONS: 4,
  DEBUG_OVERLAY_OPACITY: 0.3,
} as const;

export const INTEGRITY = {
  MIN_OVERALL_SCORE: 0.50,
  MIN_PALM_SCORE: 0.60,
  DRAWING_REQUIRED: ['WRIST', 'INDEX_TIP', 'INDEX_MCP', 'MIDDLE_MCP'] as const,
  CURSOR_REQUIRED: ['WRIST', 'INDEX_TIP', 'INDEX_MCP', 'MIDDLE_TIP', 'MIDDLE_MCP'] as const,
  ERASER_REQUIRED: ['WRIST', 'THUMB_TIP', 'INDEX_TIP', 'MIDDLE_TIP', 'RING_TIP', 'PINKY_TIP'] as const,
  STALE_LANDMARK_VALUE: 0.001,
} as const;

export const FREEZE = {
  MAX_FREEZE_MS: 300000,
  FREEZE_INTEGRITY_THRESHOLD: 0.45,
  FREEZE_EDGE_THRESHOLD: 0.95,
  UNFREEZE_INTEGRITY: 0.45,
  UNFREEZE_EDGE: 0.70,
  UNFREEZE_CONSECUTIVE_FRAMES: 2,
  TRANSITION_BLEND_FRAMES: 4,
} as const;

export const SAFE_ZONE = {
  INNER_X_MIN: 0.0,
  INNER_X_MAX: 1.0,
  INNER_Y_MIN: 0.0,
  INNER_Y_MAX: 1.0,
  COMPRESSION_STRENGTH: 0.65,
  BOTTOM_COMPRESSION: 0.50,
} as const;

export const FALLBACK = {
  DRAW_BUTTON: 0,
  ERASE_BUTTON: 2,
  COLOR_CYCLE_KEY: 'KeyC',
  CLEAR_KEY: 'KeyX',
  UNDO_KEY: 'KeyZ',
} as const;
