import { LANDMARK_INDICES as L } from './types';

export const WEBCAM = {
  WIDTH: 1280,
  HEIGHT: 720,
  FPS: 60,
  FACING_MODE: 'user',
} as const;

export const INFERENCE = {
  EVERY_NTH_FRAME: 1,
  MAX_HANDS: 2,
  MIN_HAND_DETECTION_CONFIDENCE: 0.55,
  MIN_HAND_TRACKING_CONFIDENCE: 0.45,
  MODEL_PATH: '/models/hand_landmarker.task',
  DELEGATE: 'CPU' as const,
  MIN_INTERVAL_MS: 0,
  CACHED_HAND_MAX_AGE_MS: 260,
  HAND_MATCH_DISTANCE: 0.28,
} as const;

export const GESTURE = {
  DEBOUNCE_FRAMES: 3,
  COOLDOWN_MS: 200,
  CLEAR_HOLD_MS: 2000,
  MIN_CONFIDENCE: 0.5,
  FINGER_EXTENSION_THRESHOLD: 0.08,
  THUMB_EXTENSION_THRESHOLD: 0.12,
  FIST_THRESHOLD: 0.12,
  TWO_FINGER_MAX_SEPARATION: 0.12,
  ACTIVATE_FRAMES: 5,
  DEACTIVATE_FRAMES: 5,
  HAND_SCALE_REFERENCE: 0.22,
  FINGER_ANGLE_EXTENDED_MAX: 0.50,
  FINGER_ANGLE_CURLED_MIN: 0.72,
  FINGER_ANGLE_OPEN_MAX: 0.60,
  EXTENSION_SCORE_MIN: 0.30,
  DRAWING_INDEX_SCORE_MIN: 0.45,
  DRAWING_CURLED_SCORE_MAX: 0.15,
  DRAWING_THUMB_CURLED_MAX: 0.30,
  HEX_ASYMMETRY_DRAWING: 2.0,
  PINCH_DISTANCE_ON: 0.08,
  PINCH_DISTANCE_OFF: 0.14,
  COLOR_SELECT_COOLDOWN_MS: 500,
  GESTURE_LATCH_TIMEOUT_MS: 1500,
} as const;

export const SMOOTHING = {
  MIN_CUTOFF: 0.6,
  BETA: 0.08,
  D_CUTOFF: 1.0,
  HISTORY_SIZE: 5,
} as const;

export const DRAWING = {
  DEFAULT_WIDTH: 0.015,
  MIN_WIDTH: 0.005,
  MAX_WIDTH: 0.04,
  ERASER_MIN_WIDTH: 0.03,
  ERASER_MAX_WIDTH: 0.12,
  MIN_POINT_DISTANCE: 0.001,
  UNDO_DEPTH: 50,
  MAX_POINTS_PER_STROKE: 5000,
} as const;

export const RENDER = {
  BG_COLOR: 0x0a0a0f,
  STROKE_SEGMENTS: 8,
  HAND_OVERLAY_OPACITY: 0.3,
  GESTURE_INDICATOR_SIZE: 0.05,
} as const;

export const PERFORMANCE = {
  TARGET_FPS: 60,
  LOW_FPS_THRESHOLD: 25,
  ADAPTIVE_QUALITY_INTERVAL_MS: 5000,
  FPS_SAMPLE_WINDOW: 60,
  STORE_SYNC_INTERVAL_MS: 66,
} as const;

export const FALLBACK = {
  DRAW_BUTTON: 0,
  ERASE_BUTTON: 2,
  COLOR_CYCLE_KEY: 'KeyC',
  CLEAR_KEY: 'KeyX',
  UNDO_KEY: 'KeyZ',
} as const;

export const STORE_SYNC_INTERVAL_MS = 66;

export const Z_LAYERS = {
  CANVAS: 0,
  STROKES: 1,
  HAND_OVERLAY: 10,
  GESTURE_INDICATOR: 20,
  UI_OVERLAY: 100,
} as const;

export const FINGER_TIP_INDICES: number[] = [
  L.THUMB_TIP, L.INDEX_TIP, L.MIDDLE_TIP, L.RING_TIP, L.PINKY_TIP,
];
export const FINGER_MCP_INDICES: number[] = [
  L.THUMB_MCP, L.INDEX_MCP, L.MIDDLE_MCP, L.RING_MCP, L.PINKY_MCP,
];
export const FINGER_PIP_INDICES: number[] = [
  L.THUMB_IP, L.INDEX_PIP, L.MIDDLE_PIP, L.RING_PIP, L.PINKY_PIP,
];
